### PR TITLE
Added method to be able to delete and update plan services

### PR DESCRIPTION
**Pull request by AlexRex**

### CODE REVIEW

**Comment by AlexRex** [comment]
@schovi what do you think about adding this endpoint?

**Comment by schovi** [comment]
@AlexRex Feel free to add anything.
Initially, I took it from https://github.com/Cox-Automotive/mashery-node/blob/master/lib/mashery.js#L72 which is 2 years old.

PS: one great thing about this API is that you don't need to call endpoint for each nested entity, but when you provide whole nested structure to the top level entity it will update nested too.
For packages:

PUT /package/:packageId
```javascript
{
  name: "Package",
  plans: [
    {
      id: "id for existing plan",
      name: "Plan 1",
      services: [
        {
          id: "id for existing service",
          name: "Service 1"
        },
        // When plan previously had this service and you exclude it
        // Then it will be removed from that plan
        // {
        //   id: "if for another existing service",
        //   name: "Service 2"
        // }
      ]
    }
  ]
}
```

**Comment by AlexRex** [comment]
@schovi Yes! That's why I liked. At the beginning I thought you have to go entity by entity in the nested tree, but actually is much more easier to manage it like that because you can update or create the nested entities from the parent.

**Comment by schovi** [comment]
https://github.com/adidas-group/mashery-toolbelt/releases/tag/v2.0.33

**Pull request merged**
